version: "3.8"
services:
  apache:
#    build:
#      context: ./apache_host
#      dockerfile: Docker-apache
    image: ikuchin/apache_entry:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - type: bind
        source: ./
        target: /data
    secrets:
      - supersecret
    configs:
      - source: user_config
        target: /usr/local/share/www.connme.ru/config/config.sh
  vhost1:
#    build:
#      context: ./apache_vhost
#      dockerfile: Docker-client1
    image: ikuchin/apache-php:v2.0
    volumes:
      - type: volume
        source: storage
        target: /storage
    networks:
      - default
      - net12
  vhost2:
#    build:
#      context: ./apache_vhost
#      dockerfile: Docker-client1
    image: ikuchin/apache-php:v2.0
#    ports:
#      - "8083:80"
    volumes:
      - type: volume
        source: storage
        target: /storage
    networks:
      - default
      - net12
  vhost3:
#    build:
#      context: ./apache_vhost
#      dockerfile: Docker-client1
    image: ikuchin/apache-php:v2.0
    volumes:
      - type: volume
        source: storage
        target: /storage

volumes:
  storage:

networks:
  default:
  net12:

secrets:
  supersecret:
    file: secret.txt

configs:
  user_config:
    file: config.txt
